### PR TITLE
Modernizing

### PR DESCRIPTION
**Pull request by agirorn**
I was unable to install this module when using node.js version 12 I went to town on it and I hope you like it.

Allow this module to be installed on modern node.js versions by removing
the engines. Linting using eslint and removed redundant modules and
variables.

Also did some refactoring.

### CODE REVIEW

**Comment by mayo** [comment]
@agirorn I no longer use metalsmith or this module. Would you be interested in adopting it?

**Comment by agirorn** [comment]
Are you talking about adopting the npm module https://www.npmjs.com/package/metalsmith-title or just this repo?

**Comment by mayo** [comment]
@agirorn This git repo. The npm module you link to is not mine. It was published from the original git repo (by OzzyCzech), which mine was forked from.

**Comment by agirorn** [comment]
I have already forked this repo and modernized it for my self and published the result of that to npmjs.com here https://www.npmjs.com/package/@agirorn/metalsmith-title.

Do anything more?

**Comment by agirorn** [comment]
@OzzyCzech granted my access to the original npm [metalsmith-title](https://www.npmjs.com/package/metalsmith-title) and I have published all these changes there.

Thanks for all your help and keeping the code alive.

**Pull request closed without merging**
